export const dior= [
  {
    "id": 1,
    "Image": "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw3b6543bf/Y0319000/Y0319000_C031900072_E01_ZHC.jpg?sw=3000&sh=2000",
    "title": "Dior Addict Lip Maximizer Gloss",
    "description":"The Dior Addict Lip Maximizer Gloss is a luxurious lip enhancer that combines intense hydration and a plumping effect for a smooth, fuller-looking pout. Formulated with hyaluronic acid, it provides long-lasting moisture while creating a glossy, mirror-like shine. Each shade enhances the natural color of your lips, offering a delicate tint that adapts to all skin tones. Lightweight and non-sticky, this gloss delivers a refreshing minty sensation upon application, leaving lips instantly refreshed. Whether worn alone for a subtle glow or layered over lipstick for added dimension, this gloss is a must-have for luxurious lip care with a touch of glamour.",
    "Category": "Lips",
    "price": "44.00", 
  },
  {
    "id": 2,
    "Image": "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dwc6750e65/Y0996398/Y0996398_C023600020_E01_ZHC.jpg?sw=3000&sh=2000",
    "title": "Dior Forever Skin Glow",
    "description":"Dior Forever Skin Glow is a radiant foundation that delivers a flawless, luminous finish for up to 24 hours. Enriched with wild pansy extract, it hydrates and smooths skin, while offering medium-to-full coverage to conceal imperfections. With SPF 35 for sun protection, this foundation provides a natural, glowing complexion that adapts to all skin tones. Lightweight and breathable, it ensures a healthy, radiant look without caking or settling into fine lines. Perfect for daily wear, Dior Forever Skin Glow combines comfort, lasting power, and an effortless glow.",
    "Category": "Face",
    "price": "69.7", 
  },
  {
    "id": 3,
    "Image": "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dwad0e8868/Y0365250/Y0365250_C036525090_E01_ZHC.jpg?sw=3000&sh=2000",
    "title": "Diorshow Iconic Overcurl Mascara",
    "description":"Diorshow Iconic Overcurl Mascara is a high-performance formula that delivers intense volume, curl, and definition. The curved brush lifts and curls each lash from root to tip, while the cotton nectar-enriched formula nourishes and strengthens lashes. Offering deep, rich color, this mascara resists smudging, flaking, and clumping, even in humid conditions. Available in classic black and brown, it creates a dramatic, wide-eyed look that lasts all day, perfect for both day and evening wear. Diorshow Iconic Overcurl Mascara provides luxurious, voluminous lashes with a single application.",
    "Category": "Eyes",
    "price": "49.21", 
  },
  {
   "id": 4,
   "Image": "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw10675a40/Y0293000/Y0293000_C029300020_E01_ZHC.jpg?sw=3000&sh=2000",
   "title": "Dior Forever Natural Velvet Compact Foundation",
   "description":"Dior Forever Natural Velvet Compact Foundation is a luxurious, long-wear foundation that offers a matte, velvety finish with lightweight coverage. Made with 90% natural-origin ingredients, it provides a naturally flawless look while maintaining skin hydration throughout the day. Enriched with wild pansy extract, it blurs imperfections and minimizes pores, creating a radiant yet matte complexion. Resistant to heat and humidity, it offers up to 24 hours of wear without smudging or caking. The sleek, refillable compact is perfect for on-the-go touch-ups and adapts to all skin tones for a natural, sophisticated finish.",
   "Category": "Face",
   "price": "72.17", 
  },
  {
   "id": 5,
   "Image": "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw25713b0a/Y0996265/Y0996265_C025400999_E01_ZHC.jpg?sw=3000&sh=2000",
   "title": "Rouge Dior Forever Liquid Lipstick",
   "description":"Rouge Dior Forever Liquid Lipstick is an ultra-pigmented, transfer-proof formula that delivers intense color with a velvety matte finish. Lasting up to 12 hours, it resists smudging, fading, and transferring. Infused with nourishing wild pansy extract, it keeps lips comfortable without drying out. Available in a range of shades, it suits all skin tones and features a precision applicator for a flawless, bold look in one swipe. Offering timeless elegance and enduring wear, this liquid lipstick is perfect for both day and night.",
   "Category": "Lips",
   "price": "51.38", 
  },
  {
   "id": 6,
   "Image": "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dwf0abd54d/Y0373000/Y0373000_C037300001_E01_ZHC.jpg?sw=3000&sh=2000",
   "title": "Rossy Glow",
   "description":"Rossy Glow is a vibrant, long-lasting blush that delivers a naturally radiant, rosy flush to the cheeks, perfect for achieving that ‘just-pinched’ look. Its unique formula adapts to the skin’s moisture level, giving each wearer a customized, fresh glow that enhances their natural beauty. Enriched with fine pigments and hydrating ingredients, Rossy Glow blends effortlessly into the skin, providing buildable coverage from a sheer, delicate tint to a more intense color. This lightweight, silky powder applies smoothly without caking or settling, ensuring a flawless finish that lasts all day. Housed in a chic, travel-friendly compact, Rossy Glow is ideal for touch-ups, adding a healthy, luminous finish anytime, anywhere. Ideal for all skin tones, this universally flattering blush embodies Dior’s commitment to timeless elegance and effortless beauty, making it a staple for any makeup lover seeking a natural, fresh-faced glow.",
   "Category": "Face",
   "price": "41.88", 
  },
  {
   "id": 7,
   "Image": "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dwf4415fbd/Y0015002/Y0015002_C001500005_E01_ZHC.jpg?sw=3000&sh=2000",
   "title": "Dior Backstage Glow Face Palette",
   "description":"The Dior Backstage Glow Face Palette is a professional-grade highlighter that provides a customizable, radiant glow. With shimmering powders in versatile shades, it enhances all skin tones, offering buildable coverage from a soft glow to a bold shine. Enriched with light-reflecting pigments, it adds dimension and highlights the skin’s natural beauty. Suitable for use on the face, eyes, and body, this multifunctional palette is perfect for layering or wearing alone. Compact and travel-friendly, it delivers a flawless, luminous finish for a radiant, camera-ready complexion anytime.",
   "Category": "Face",
   "price": "88.43", 
  },
  {
   "id": 8,
   "Image": "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw81af9a42/Y0003502/Y0003502_C000350401_E01_ZHC.jpg?sw=3000&sh=2000",
   "title": "Dior Airfalsh Spray Foundation",
   "description":"Dior Airflash Spray Foundation is an ultra-lightweight foundation that delivers a flawless, airbrushed finish with effortless application. Using micro-diffusion technology, it releases a fine mist that blends seamlessly, providing buildable coverage for a natural to full-coverage look. Enriched with light-diffusing pigments, it blurs imperfections and minimizes pores for a radiant glow. The long-lasting, water-resistant formula ensures fresh, flawless makeup for hours. Perfect for all skin types, it offers professional-grade results with a convenient, easy-to-apply spray, making it a must-have for a weightless, high-performance foundation.",
   "Category": "Face",
   "price": "77.32", 
  },
  {
   "id": 9,
   "Image": "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw6f8d5705/Y0326000/Y0326000_C032600010_E01_ZHC.jpg?sw=3000&sh=2000",
   "title": "Dior Forever Skin Correct Concealer",
   "description":"The Dior Forever Skin Correct Concealer is a high-coverage, long-wear concealer that perfects the complexion with a natural finish. Enriched with wild pansy extract and rosehip, it nourishes and hydrates while providing seamless coverage for dark circles, blemishes, and redness. Its creamy, blendable formula ensures up to 24-hour wear, resisting creasing and fading for a fresh look all day. Lightweight and non-drying, it offers buildable coverage in a wide range of shades, ideal for both spot correction and all-over perfection, making it a staple for a flawless, radiant finish.",
   "Category": "Face",
   "price": "49.77", 
  },
  {
   "id": 10,
   "Image": "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw0c8bef9b/Y0997161/Y0997161_C099700456_E01_ZHC.jpg?sw=3000&sh=2000",
   "title": "Diorsnow UV Shield",
   "description":"The Diorsnow UV Shield is a powerful sunscreen offering SPF 50+ PA++++ protection, designed to shield skin from harmful UVA and UVB rays while enhancing its natural radiance. Infused with Dior’s exclusive Edelweiss Complex, this lightweight, non-greasy formula not only defends against environmental pollutants and free radicals but also brightens and hydrates the skin, helping to reduce the appearance of dark spots and uneven tone over time. Suitable for all skin types, the Diorsnow UV Shield provides a smooth, fresh finish that feels comfortable all day, making it a perfect addition to any skincare routine for luminous, protected skin.",
   "Category": "Face",
   "price": "24.16", 
  },
]